### PR TITLE
fix(vtt): remove replacement of new lines in caption content

### LINKED ISSUE #4: bug(vtt): multiline caption new line removal
As stated in #2 before, currently new lines in multiline captions are replaced with spaces which can cause a problem in the captions that have more than one speaker at the current time of the video. In this situtation, subtitle editors mostly denote each speaker with a hyphen (-), words they say and a new line. Hence resulting in outputs as `-Where were you? - At the store`.
This may confuse people when reading the caption because of this I suggest keeping the content of the caption as it is.

### PR DESCRIPTION
**Pull request by frost768**
Reason for this PR is described in (fix #4)

### CODE REVIEW

**Review by leranjun — APPROVED** [review]
LGTM

**Comment by frost768** [comment]
I'm sure these changes is not enough for a new version but are you planing on releasing one anytime soon?
I want to keep using the official repo in an another project.

**Comment by leranjun** [comment]
> I'm sure these changes are not enough for a new version but are you planning on releasing one anytime soon? I want to keep using the official repo in an another project.

Haha, you read my mind! I'm just trying to set up some automations on this repo to make releasing and CI easier (you might have noticed Deepsource I added just now 😁). Are you in a hurry? I can publish a patch on NPM first if you need to close https://github.com/movie-web/movie-web/issues/269 now. Otherwise I'll try to figure this out first.

**Comment by frost768** [comment]
Not really, it doesn't affect project's functionality as far as I'm concerned but I think it would be better to get project's authors' opinions on this matter. I'll inform you on their decision.

**Comment by leranjun** [comment]
@frost768 Release Please didn't work very well, but 2.1.1 should now be live on NPM!

**Comment by frost768** [comment]
Many thanks @leranjun!

**Pull request merged**
